# Site settings
title:       Dr. Skeleton's Art School
description: Takes and japes from your favorite professors
url:         http://drskeleton.art
locale:      en_US

name:  Dr. Skeleton's Art School
email: drskeletonsartschool@gmail.com

permalink: /:title.html

# Build settings
markdown: kramdown
